### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by orfevre2013** [CakeDC/ratings#27] opened 2015-12-03 12:24 UTC
hello
thank you for this plugin. I have an issue on installation. I'm working on remote server, I cannot use cake terminal to install the plugin's table on my database so i use migration file to do it manually, then I have followed the quickstart and install the plugin. Since I try to reach the website i have sql error :
Database Error

Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'isRatedBy' at line 1

SQL Query: isRatedBy

Notice: If you want to customize this error message, create app/View/Errors/pdo_error.ctp
Can you help me please?

**Comment by omnuvito** [comment] 2015-12-05 04:13
Hi @orfevre2013, I create a CakePHP 2.x project (2.7.0) and I created the table as you indicated above. I followed the Quick Start tutorial unable to reproduce the issue. Did you read in detail the Quick Start tutorial? this specifies that the plugin does not work if the Auth component is not used. Try adding the Auth component to the controller. I hope will be helpful. Here you can find how to configure components: [Components 2.x](http://book.cakephp.org/2.0/en/controllers/components.html)

**Comment by orfevre2013** [comment] 2015-12-05 10:12
hi
thank you for you answer. I'm using Auth component and I declare it in app controller, do I need to redeclare it in my controller? I'm trying to set rating for a company profile. Do I need to put auth component in his controller? Can you give me the sql code to create the ratings table? may be i'm missing something at this step. Best regards

**Comment by omnuvito** [comment] 2015-12-05 15:27
Sure @orfevre2013, here it is:
```
CREATE TABLE ratings(
	id VARCHAR(36) NOT NULL,
	user_id VARCHAR(36) NOT NULL,
	foreign_key VARCHAR(36) NOT NULL,
	model VARCHAR(255) NOT NULL,
	value FLOAT(8,4) NULL DEFAULT '0.000',
	created DATETIME NULL,
	modified DATETIME NULL,
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX UNIQUE_RATING ON ratings (user_id, foreign_key, model);
```

**Comment by orfevre2013** [comment] 2015-12-05 23:21
Thank you for your quick answer. The issue still remain. Dont know why.

**Comment by omnuvito** [comment] 2015-12-06 13:52
@orfevre2013 Could you check that any fields of the tables have a SQL reserved word?

**Comment by orfevre2013** [comment] 2015-12-06 20:02
Hi
I have checked, there is no  SQl reserved word. do you mind if i give 
you my web site's login credentials to help solve the issue?
Bests regards
Le 06/12/2015 14:52, José Alejandro Alvarez Mendoza a écrit :
>
> @orfevre2013 <https://github.com/orfevre2013> Could you check that any 
> fields of the tables have a SQL reserved word?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CakeDC/ratings/issues/27#issuecomment-162319459>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by Megslalk** [comment] 2016-02-15 13:24
Hi, Closing this issue, please reopen if unresolved, thanks!

**Closed by Megslalk** 2016-02-15 13:24 UTC
